# Generated by Django 3.2.16 on 2023-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_avatar',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images'),
        ),
    ]
