# Generated by Django 3.2.16 on 2023-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_auto_20230526_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('skill', models.TextField(blank=True, max_length=230, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
