# Generated by Django 3.2.16 on 2023-08-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='avatar',
            field=models.ImageField(default='15', null=True, upload_to=''),
        ),
    ]
