# Generated by Django 3.2.16 on 2023-08-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_auto_20230814_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='mycv',
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
