# Generated by Django 3.2.16 on 2023-08-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_auto_20230816_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
