# Generated by Django 3.2.16 on 2023-08-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_delete_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
