# Generated by Django 3.2.16 on 2023-08-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0024_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='avatar',
            field=models.ImageField(default='home.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
    ]
