# Generated by Django 3.2.16 on 2023-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0025_auto_20230818_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='num',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default='about.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='contact_me.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='comming_soon.jpg', null=True, upload_to='project_images'),
        ),
    ]
