# Generated by Django 3.2.16 on 2023-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0026_auto_20230827_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='comming_soon.jpg', null=True, upload_to=''),
        ),
    ]
