# Generated by Django 3.2.16 on 2023-08-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0028_auto_20230827_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
