# Generated by Django 3.2.16 on 2023-08-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0030_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
