# Generated by Django 3.2.16 on 2023-08-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0039_auto_20230831_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
