# Generated by Django 3.2.16 on 2023-09-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0047_auto_20230904_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='image',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='avatar',
            field=models.ImageField(default='images/alina.webp', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default='images/about_me_3.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='images/contact_me.svg', null=True, upload_to=''),
        ),
    ]
