# Generated by Django 3.2.16 on 2023-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0049_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=50, null=True),
        ),
    ]
