name_complete = "Alina Bazavan"
avatar = "C:\\Users\\Amalia\\ALINA\\DJANGO\\PORTFOLIO\\portfolio_app\\static\\images\\avatar\\15.png"
mini_about = "I am currently a self taught programmer, a Python/Django developer and I am continuously learning new stacks. \
    I am passionate about finding ideas, conceptualizing and producing customer-centric and technology enabled products from scratch."
address = "Romania, Europe"
phone = "+04 0767 970 718"
email = "sempedia@gmail.com"
instagram = ""
twitter = ""
facebook = ""
github = "https://github.com/sempedia"
linkedin = ""
mycv = ""
description1 = ""
description2 =""
about_avatar =""
skill = "[]"
num = ""